export enum ACCOUNT_TYPE{
    LOAD_ACCOUNT_START='LOAD_ACCOUNT_START',
    LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS',
    LOAD_ACCOUNT_FAIL = 'LOAD_ACCOUNT_FAIL'
}

export enum NETWORK_TYPE{
    LOAD_NETWORKID_START='LOAD_NETWORKID_START',
    LOAD_NETWORKID_SUCCESS = 'LOAD_NETWORKID_SUCCESS',
    LOAD_NETWORKID_FAIL = 'LOAD_NETWORKID_FAIL'
}

export enum CONTRACT_TYPE{
    LOAD_CONTRACT_START='LOAD_CONTRACT_START',
    LOAD_CONTRACT_SUCCESS = 'LOAD_CONTRACT_SUCCESS',
    LOAD_CONTRACT_FAIL = 'LOAD_CONTRACT_FAIL'
}
export enum ALERT_TYPE{
    ALERT_PROCESSING='ALERT_PROCESSING',
    ALERT_SUCCESS = 'ALERT_SUCCESS',
    ALERT_FAIL = 'ALERT_FAIL',
    ALERT_INIT ='ALERT_INIT'
}

export enum STAKE_TYPE{
    STAKE_START='STAKE_START',
    STAKE_SUCCESS = 'STAKE_SUCCESS',
    STAKE_FAIL = 'STAKE_FAIL'
}

export enum CLAIM_REWARD_TYPE{
    CLAIM_REWARD_START='CLAIM_REWARD_START',
    CLAIM_REWARD_SUCCESS = 'CLAIM_REWARD_SUCCESS',
    CLAIM_REWARD_FAIL = 'CLAIM_REWARD_FAIL'
}

export enum WITHDRAW_TYPE{
    WITHDRAW_START='WITHDRAW_START',
    WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS',
    WITHDRAW_FAIL = 'WITHDRAW_FAIL'
}

export enum STAKING_TYPE{
    STAKING_DATA_LOAD_START='STAKING_DATA_LOAD_START',
    STAKING_DATA_LOAD_SUCCESS = 'STAKING_DATA_LOAD_SUCCESS',
    STAKING_DATA_LOAD_FAIL = 'STAKING_DATA_LOAD_FAIL'
}

export enum GET_BALANCES_TYPE{
    GET_BALANCES_START='GET_BALANCES_START',
    GET_BALANCES_SUCCESS = 'GET_BALANCES_SUCCESS',
    GET_BALANCES_FAIL = 'GET_BALANCES_FAIL'
}